apiVersion: v1
kind: Pod
spec:
  containers:
  - name: py27
    image: circleci/python:2.7
    resources:
        requests:
          cpu: 1
    command:
    - cat
    tty: true
    securityContext:
        runAsUser: 0
        priviliged: true
nodeSelector:
  instance-type: spot-large